language: r
sudo: false
cache: packages

warnings_are_errors: false

notifications:
  email:
    - leo.lahti@iki.fi

r_packages:
  - Cairo
  
r_github_packages:
  - jimhester/covr
  
after_success:
  - Rscript -e 'covr::codecov()'

