language: r
sudo: false
cache: packages

warnings_are_errors: false

before_install:
  - pip install --user codecov

r_packages:
  - Cairo
  
after_success:
  - bash <(curl -s https://codecov.io/bash)